# CV32E40P ALU Test Assembly Program
# Generated by asm_generator.py
# Copyright 2024 ChipAgents

.section .text
.global _start

_start:
    # Directed Test Cases
    add      x1, x0, x0           // ADD x1, zero, zero (result = 0)
    add      x2, x1, x1           // ADD x2, x1, x1 (double)
    sub      x3, x2, x1           // SUB x3, x2, x1
    addi     x4, x0, 2147483647   // ADDI x4, zero, MAX_INT
    addi     x5, x0, -2147483648  // ADDI x5, zero, MIN_INT
    andi     x6, x4, -1           // ANDI x6, x4, 0xFFFFFFFF
    ori      x7, x0, 1431655765   // ORI x7, zero, 0x55555555
    xori     x8, x7, -1431655766  // XORI x8, x7, 0xAAAAAAAA
    and      x9, x7, x8           // AND x9, x7, x8 (should be 0)
    or       x10, x7, x8          // OR x10, x7, x8 (should be 0xFFFFFFFF)
    slli     x11, x4, 1           // SLLI x11, x4, 1 (left shift by 1)
    srli     x12, x4, 1           // SRLI x12, x4, 1 (logical right shift)
    srai     x13, x5, 1           // SRAI x13, x5, 1 (arithmetic right shift)
    sll      x14, x4, x1          // SLL x14, x4, x1 (variable shift)
    slt      x15, x5, x4          // SLT x15, MIN_INT, MAX_INT (should be 1)
    sltu     x16, x4, x5          // SLTU x16, MAX_INT, MIN_INT (unsigned)
    slti     x17, x4, 0           // SLTI x17, MAX_INT, 0
    sltiu    x18, x0, 1           // SLTIU x18, zero, 1
    slt      x24, x9, x8          // SLT x24, x9, x8
    xori     x4, x22, -1336       // XORI x4, x22, -1336
    sll      x1, x3, x7           // SLL x1, x3, x7
    ori      x1, x18, 16          // ORI x1, x18, 16
    sub      x23, x14, x11        // SUB x23, x14, x11
    or       x31, x25, x11        // OR x31, x25, x11
    subi     x4, x12, 118         // SUBI x4, x12, 118
    xori     x20, x29, -473       // XORI x20, x29, -473
    andi     x9, x30, -249        // ANDI x9, x30, -249
    slt      x8, x27, x2          // SLT x8, x27, x2
    srai     x11, x7, 31          // SRAI x11, x7, 31
    srai     x15, x5, 16          // SRAI x15, x5, 16
    addi     x24, x19, 1223       // ADDI x24, x19, 1223
    slli     x13, x20, 29         // SLLI x13, x20, 29
    srli     x28, x31, 0          // SRLI x28, x31, 0
    slt      x22, x29, x18        // SLT x22, x29, x18
    ori      x30, x1, 1954        // ORI x30, x1, 1954

    # Random Test Cases
    remu     x8, x15, x28         // REMU x8, x15, x28
    remu     x18, x4, x18         // REMU x18, x4, x18
    div      x22, x8, x3          // DIV x22, x8, x3
    div      x13, x9, x12         // DIV x13, x9, x12
    xor      x7, x22, x9          // XOR x7, x22, x9
    div      x20, x21, x8         // DIV x20, x21, x8
    remu     x9, x3, x7           // REMU x9, x3, x7
    srl      x17, x16, x3         // SRL x17, x16, x3
    div      x5, x21, x14         // DIV x5, x21, x14
    rem      x4, x10, x1          // REM x4, x10, x1
    brev     x9, x17              // BREV x9, x17
    div      x28, x21, x10        // DIV x28, x21, x10
    srl      x5, x12, x25         // SRL x5, x12, x25

    # Program termination
    addi    x1, x0, 93      // sys_exit
    addi    x10, x0, 0      // exit status
    ecall                   // system call
