# CV32E40P ALU Test Assembly Program
# Generated by asm_generator.py
# Copyright 2024 ChipAgents

.section .text
.global _start

_start:
    # Directed Test Cases
    add      x1, x0, x0           // ADD x1, zero, zero (result = 0)
    add      x2, x1, x1           // ADD x2, x1, x1 (double)
    sub      x3, x2, x1           // SUB x3, x2, x1
    addi     x4, x0, 2147483647   // ADDI x4, zero, MAX_INT
    addi     x5, x0, -2147483648  // ADDI x5, zero, MIN_INT
    andi     x6, x4, -1           // ANDI x6, x4, 0xFFFFFFFF
    ori      x7, x0, 1431655765   // ORI x7, zero, 0x55555555
    xori     x8, x7, -1431655766  // XORI x8, x7, 0xAAAAAAAA
    and      x9, x7, x8           // AND x9, x7, x8 (should be 0)
    or       x10, x7, x8          // OR x10, x7, x8 (should be 0xFFFFFFFF)
    slli     x11, x4, 1           // SLLI x11, x4, 1 (left shift by 1)
    srli     x12, x4, 1           // SRLI x12, x4, 1 (logical right shift)
    srai     x13, x5, 1           // SRAI x13, x5, 1 (arithmetic right shift)
    sll      x14, x4, x1          // SLL x14, x4, x1 (variable shift)
    slt      x15, x5, x4          // SLT x15, MIN_INT, MAX_INT (should be 1)
    sltu     x16, x4, x5          // SLTU x16, MAX_INT, MIN_INT (unsigned)
    slti     x17, x4, 0           // SLTI x17, MAX_INT, 0
    sltiu    x18, x0, 1           // SLTIU x18, zero, 1
    and      x24, x9, x8          // AND x24, x9, x8
    add      x22, x24, x29        // ADD x22, x24, x29
    ori      x14, x2, -1804       // ORI x14, x2, -1804
    sub      x17, x20, x1         // SUB x17, x20, x1
    xori     x21, x23, 1388       // XORI x21, x23, 1388
    addi     x26, x28, -1995      // ADDI x26, x28, -1995
    sub      x31, x25, x11        // SUB x31, x25, x11
    subi     x4, x12, 769         // SUBI x4, x12, 769
    and      x24, x15, x18        // AND x24, x15, x18
    subi     x3, x18, 353         // SUBI x3, x18, 353
    slti     x19, x7, -1479       // SLTI x19, x7, -1479
    sub      x25, x10, x3         // SUB x25, x10, x3
    slt      x13, x9, x15         // SLT x13, x9, x15
    addi     x23, x30, -1464      // ADDI x23, x30, -1464
    or       x18, x24, x8         // OR x18, x24, x8
    subi     x9, x30, -249        // SUBI x9, x30, -249
    sll      x8, x27, x2          // SLL x8, x27, x2
    sltiu    x9, x3, x7           // SLTIU x9, x3, x7
    subi     x5, x9, -905         // SUBI x5, x9, -905
    addi     x24, x19, 1461       // ADDI x24, x19, 1461
    sltiu    x12, x8, x5          // SLTIU x12, x8, x5
    and      x25, x2, x28         // AND x25, x2, x28
    sub      x26, x22, x14        // SUB x26, x22, x14
    andi     x13, x20, 1786       // ANDI x13, x20, 1786
    ori      x28, x31, -1954      // ORI x28, x31, -1954
    sll      x22, x29, x18        // SLL x22, x29, x18
    srai     x11, x4, 18          // SRAI x11, x4, 18
    andi     x1, x31, 109         // ANDI x1, x31, 109
    slti     x27, x21, -419       // SLTI x27, x21, -419
    sub      x18, x31, x25        // SUB x18, x31, x25
    and      x30, x12, x29        // AND x30, x12, x29
    add      x3, x24, x16         // ADD x3, x24, x16
    sltu     x5, x22, x16         // SLTU x5, x22, x16
    addi     x15, x29, 1650       // ADDI x15, x29, 1650
    sub      x3, x11, x1          // SUB x3, x11, x1
    or       x19, x8, x1          // OR x19, x8, x1
    add      x8, x3, x29          // ADD x8, x3, x29
    addi     x3, x17, -99         // ADDI x3, x17, -99
    subi     x7, x18, -965        // SUBI x7, x18, -965
    srli     x19, x16, 15         // SRLI x19, x16, 15
    slli     x7, x4, 6            // SLLI x7, x4, 6
    slt      x22, x21, x21        // SLT x22, x21, x21
    subi     x24, x11, -1153      // SUBI x24, x11, -1153
    sub      x18, x15, x5         // SUB x18, x15, x5
    add      x3, x30, x25         // ADD x3, x30, x25
    sltu     x14, x16, x16        // SLTU x14, x16, x16
    subi     x29, x2, -700        // SUBI x29, x2, -700
    subi     x9, x30, 1679        // SUBI x9, x30, 1679
    subi     x5, x7, 382          // SUBI x5, x7, 382
    add      x19, x24, x18        // ADD x19, x24, x18
    addi     x2, x2, 1857         // ADDI x2, x2, 1857
    ori      x6, x2, -1392        // ORI x6, x2, -1392
    slt      x20, x3, x22         // SLT x20, x3, x22
    sltiu    x4, x31, x29         // SLTIU x4, x31, x29
    ori      x20, x2, -1377       // ORI x20, x2, -1377
    ori      x19, x17, 543        // ORI x19, x17, 543
    subi     x5, x22, 409         // SUBI x5, x22, 409
    and      x1, x15, x20         // AND x1, x15, x20
    or       x30, x12, x29        // OR x30, x12, x29
    sub      x12, x10, x6         // SUB x12, x10, x6
    ori      x23, x10, -1984      // ORI x23, x10, -1984
    srli     x10, x30, 6          // SRLI x10, x30, 6
    sltu     x9, x10, x20         // SLTU x9, x10, x20
    addi     x7, x22, 114         // ADDI x7, x22, 114
    subi     x27, x9, -1687       // SUBI x27, x9, -1687
    sub      x21, x9, x6          // SUB x21, x9, x6
    srli     x23, x14, 0          // SRLI x23, x14, 0
    sub      x18, x2, x27         // SUB x18, x2, x27
    sub      x14, x5, x2          // SUB x14, x5, x2
    add      x29, x12, x7         // ADD x29, x12, x7
    srai     x4, x12, 26          // SRAI x4, x12, 26
    sltu     x29, x14, x1         // SLTU x29, x14, x1
    addi     x26, x30, 1324       // ADDI x26, x30, 1324
    sltu     x9, x6, x26          // SLTU x9, x6, x26
    slli     x28, x2, 30          // SLLI x28, x2, 30
    subi     x12, x10, -184       // SUBI x12, x10, -184
    sub      x13, x11, x9         // SUB x13, x11, x9
    slti     x12, x21, 1226       // SLTI x12, x21, 1226
    srli     x11, x31, 1          // SRLI x11, x31, 1
    addi     x6, x19, 126         // ADDI x6, x19, 126
    subi     x12, x24, 521        // SUBI x12, x24, 521
    ori      x4, x13, -491        // ORI x4, x13, -491
    subi     x1, x17, -434        // SUBI x1, x17, -434
    add      x31, x22, x30        // ADD x31, x22, x30
    addi     x22, x28, -1028      // ADDI x22, x28, -1028
    andi     x23, x10, -1006      // ANDI x23, x10, -1006
    subi     x22, x24, -623       // SUBI x22, x24, -623
    addi     x7, x14, 591         // ADDI x7, x14, 591
    andi     x22, x7, 1828        // ANDI x22, x7, 1828
    srai     x6, x22, 5           // SRAI x6, x22, 5
    addi     x3, x27, -124        // ADDI x3, x27, -124
    sub      x16, x20, x28        // SUB x16, x20, x28
    slli     x14, x29, 12         // SLLI x14, x29, 12
    slli     x16, x13, 15         // SLLI x16, x13, 15
    add      x29, x25, x28        // ADD x29, x25, x28
    sll      x25, x14, x8         // SLL x25, x14, x8
    subi     x2, x18, -7          // SUBI x2, x18, -7
    slti     x31, x25, 1577       // SLTI x31, x25, 1577
    xori     x29, x17, 1447       // XORI x29, x17, 1447
    sltiu    x29, x6, x24         // SLTIU x29, x6, x24
    sltiu    x9, x25, x8          // SLTIU x9, x25, x8
    slti     x25, x25, 1921       // SLTI x25, x25, 1921
    addi     x11, x11, -1388      // ADDI x11, x11, -1388
    sub      x13, x23, x5         // SUB x13, x23, x5
    sll      x14, x14, x11        // SLL x14, x14, x11
    andi     x2, x7, 1393         // ANDI x2, x7, 1393
    add      x28, x29, x25        // ADD x28, x29, x25
    andi     x1, x31, 833         // ANDI x1, x31, 833
    subi     x28, x29, 1384       // SUBI x28, x29, 1384
    xori     x18, x26, -242       // XORI x18, x26, -242
    subi     x24, x6, 1780        // SUBI x24, x6, 1780
    xori     x1, x3, 1463         // XORI x1, x3, 1463
    subi     x6, x2, 83           // SUBI x6, x2, 83
    sub      x15, x11, x11        // SUB x15, x11, x11
    slli     x9, x25, 26          // SLLI x9, x25, 26
    add      x16, x1, x24         // ADD x16, x1, x24
    srai     x2, x25, 1           // SRAI x2, x25, 1
    or       x5, x16, x22         // OR x5, x16, x22
    sub      x15, x23, x9         // SUB x15, x23, x9
    sll      x25, x27, x6         // SLL x25, x27, x6
    sub      x4, x23, x25         // SUB x4, x23, x25
    add      x26, x19, x26        // ADD x26, x19, x26
    subi     x22, x12, -1484      // SUBI x22, x12, -1484
    slt      x14, x31, x12        // SLT x14, x31, x12
    andi     x23, x5, 1519        // ANDI x23, x5, 1519
    addi     x20, x26, 1912       // ADDI x20, x26, 1912
    xori     x19, x9, 592         // XORI x19, x9, 592
    slt      x9, x29, x15         // SLT x9, x29, x15
    subi     x19, x20, 1056       // SUBI x19, x20, 1056
    subi     x28, x11, -559       // SUBI x28, x11, -559
    addi     x18, x1, -483        // ADDI x18, x1, -483
    subi     x16, x18, -80        // SUBI x16, x18, -80
    srai     x23, x16, 28         // SRAI x23, x16, 28
    sll      x10, x8, x13         // SLL x10, x8, x13
    ori      x12, x14, 661        // ORI x12, x14, 661
    subi     x9, x10, 11          // SUBI x9, x10, 11
    sub      x11, x4, x24         // SUB x11, x4, x24
    xori     x6, x7, -276         // XORI x6, x7, -276
    addi     x6, x10, -1933       // ADDI x6, x10, -1933
    xori     x31, x5, 1973        // XORI x31, x5, 1973
    add      x19, x10, x16        // ADD x19, x10, x16
    subi     x4, x27, -1513       // SUBI x4, x27, -1513
    and      x19, x21, x22        // AND x19, x21, x22
    sub      x26, x19, x31        // SUB x26, x19, x31
    sub      x4, x18, x25         // SUB x4, x18, x25
    ori      x26, x20, -200       // ORI x26, x20, -200
    slli     x15, x30, 28         // SLLI x15, x30, 28
    subi     x10, x19, -1555      // SUBI x10, x19, -1555
    xori     x4, x31, -346        // XORI x4, x31, -346
    add      x6, x1, x14          // ADD x6, x1, x14
    ori      x16, x10, -1781      // ORI x16, x10, -1781
    addi     x23, x28, 1671       // ADDI x23, x28, 1671
    sub      x30, x9, x26         // SUB x30, x9, x26
    srli     x22, x26, 12         // SRLI x22, x26, 12
    ori      x8, x21, -828        // ORI x8, x21, -828
    addi     x20, x24, 316        // ADDI x20, x24, 316
    andi     x23, x10, 1249       // ANDI x23, x10, 1249
    andi     x24, x11, 3          // ANDI x24, x11, 3
    sub      x31, x22, x27        // SUB x31, x22, x27
    slt      x25, x22, x27        // SLT x25, x22, x27
    add      x25, x25, x6         // ADD x25, x25, x6
    xori     x15, x30, 230        // XORI x15, x30, 230

    # Random Test Cases
    srl      x23, x14, x11        // SRL x23, x14, x11
    xor      x6, x12, x12         // XOR x6, x12, x12
    auipc    x7, 1046963          // AUIPC x7, 1046963
    lui      x17, 223159          // LUI x17, 223159
    lui      x20, 679804          // LUI x20, 679804
    auipc    x8, 121477           // AUIPC x8, 121477
    lui      x9, 887384           // LUI x9, 887384
    lui      x23, 653716          // LUI x23, 653716
    sra      x14, x14, x15        // SRA x14, x14, x15
    xor      x15, x8, x28         // XOR x15, x8, x28
    auipc    x26, 205329          // AUIPC x26, 205329
    lui      x22, 658891          // LUI x22, 658891
    lui      x3, 447016           // LUI x3, 447016
    lui      x9, 242071           // LUI x9, 242071
    xor      x29, x30, x28        // XOR x29, x30, x28
    lui      x30, 496474          // LUI x30, 496474
    sra      x17, x10, x22        // SRA x17, x10, x22
    xor      x13, x18, x27        // XOR x13, x18, x27
    srl      x26, x7, x5          // SRL x26, x7, x5
    lui      x15, 279632          // LUI x15, 279632
    xor      x15, x3, x23         // XOR x15, x3, x23
    xor      x14, x16, x1         // XOR x14, x16, x1
    lui      x30, 826320          // LUI x30, 826320
    xor      x8, x21, x3          // XOR x8, x21, x3
    lui      x27, 42739           // LUI x27, 42739
    srl      x20, x20, x31        // SRL x20, x20, x31
    lui      x19, 53851           // LUI x19, 53851
    auipc    x13, 415927          // AUIPC x13, 415927
    xor      x1, x28, x14         // XOR x1, x28, x14
    xor      x26, x9, x11         // XOR x26, x9, x11
    sra      x22, x19, x12        // SRA x22, x19, x12
    sra      x24, x19, x25        // SRA x24, x19, x25
    xor      x4, x27, x7          // XOR x4, x27, x7
    srl      x9, x2, x2           // SRL x9, x2, x2
    xor      x6, x31, x2          // XOR x6, x31, x2
    xor      x22, x3, x6          // XOR x22, x3, x6
    lui      x3, 125070           // LUI x3, 125070
    auipc    x15, 168698          // AUIPC x15, 168698

    # Program termination
    addi    x1, x0, 93      // sys_exit
    addi    x10, x0, 0      // exit status
    ecall                   // system call
