# CV32E40P ALU Test Assembly Program
# Generated by asm_generator.py
# Copyright 2024 ChipAgents

.section .text
.global _start

_start:
    # Directed Test Cases
    add      x1, x0, x0           // ADD x1, zero, zero (result = 0)
    add      x2, x1, x1           // ADD x2, x1, x1 (double)
    sub      x3, x2, x1           // SUB x3, x2, x1
    addi     x4, x0, 2147483647   // ADDI x4, zero, MAX_INT
    addi     x5, x0, -2147483648  // ADDI x5, zero, MIN_INT
    andi     x6, x4, -1           // ANDI x6, x4, 0xFFFFFFFF
    ori      x7, x0, 1431655765   // ORI x7, zero, 0x55555555
    xori     x8, x7, -1431655766  // XORI x8, x7, 0xAAAAAAAA
    and      x9, x7, x8           // AND x9, x7, x8 (should be 0)
    or       x10, x7, x8          // OR x10, x7, x8 (should be 0xFFFFFFFF)
    slli     x11, x4, 1           // SLLI x11, x4, 1 (left shift by 1)
    srli     x12, x4, 1           // SRLI x12, x4, 1 (logical right shift)
    srai     x13, x5, 1           // SRAI x13, x5, 1 (arithmetic right shift)
    sll      x14, x4, x1          // SLL x14, x4, x1 (variable shift)
    slt      x15, x5, x4          // SLT x15, MIN_INT, MAX_INT (should be 1)
    sltu     x16, x4, x5          // SLTU x16, MAX_INT, MIN_INT (unsigned)
    slti     x17, x4, 0           // SLTI x17, MAX_INT, 0
    sltiu    x18, x0, 1           // SLTIU x18, zero, 1
    xori     x28, x27, -1522      // XORI x28, x27, -1522
    add      x8, x25, x1          // ADD x8, x25, x1
    and      x3, x11, x29         // AND x3, x11, x29
    xori     x9, x5, -852         // XORI x9, x5, -852
    and      x26, x23, x2         // AND x26, x23, x2
    ori      x19, x3, -1192       // ORI x19, x3, -1192
    subi     x16, x22, -1473      // SUBI x16, x22, -1473
    sub      x11, x29, x20        // SUB x11, x29, x20
    xori     x31, x19, -108       // XORI x31, x19, -108
    slli     x12, x28, 7          // SLLI x12, x28, 7
    addi     x25, x21, -392       // ADDI x25, x21, -392
    subi     x17, x26, -1848      // SUBI x17, x26, -1848
    subi     x28, x29, -98        // SUBI x28, x29, -98
    and      x30, x28, x25        // AND x30, x28, x25
    ori      x26, x12, -350       // ORI x26, x12, -350
    addi     x30, x3, 1270        // ADDI x30, x3, 1270
    subi     x22, x28, -1085      // SUBI x22, x28, -1085
    subi     x30, x25, -1679      // SUBI x30, x25, -1679
    sub      x26, x30, x16        // SUB x26, x30, x16
    srai     x4, x27, 10          // SRAI x4, x27, 10
    subi     x15, x3, -1813       // SUBI x15, x3, -1813
    addi     x21, x21, 1612       // ADDI x21, x21, 1612
    xori     x20, x3, -1204       // XORI x20, x3, -1204
    slli     x25, x1, 24          // SLLI x25, x1, 24
    add      x20, x12, x29        // ADD x20, x12, x29
    and      x23, x6, x21         // AND x23, x6, x21
    slt      x19, x20, x30        // SLT x19, x20, x30
    subi     x29, x23, 1137       // SUBI x29, x23, 1137
    sub      x14, x4, x22         // SUB x14, x4, x22
    subi     x30, x14, -1894      // SUBI x30, x14, -1894
    slli     x26, x13, 21         // SLLI x26, x13, 21
    sll      x3, x9, x27          // SLL x3, x9, x27
    ori      x28, x19, 839        // ORI x28, x19, 839
    srli     x6, x24, 17          // SRLI x6, x24, 17
    addi     x12, x24, 1627       // ADDI x12, x24, 1627
    slti     x2, x12, -2022       // SLTI x2, x12, -2022
    sltu     x8, x4, x20          // SLTU x8, x4, x20
    ori      x30, x23, -881       // ORI x30, x23, -881
    addi     x30, x4, -373        // ADDI x30, x4, -373
    andi     x28, x26, 1437       // ANDI x28, x26, 1437
    sub      x28, x9, x18         // SUB x28, x9, x18
    sub      x20, x6, x19         // SUB x20, x6, x19
    srli     x21, x16, 0          // SRLI x21, x16, 0
    sub      x13, x29, x23        // SUB x13, x29, x23
    add      x26, x6, x1          // ADD x26, x6, x1
    and      x15, x14, x24        // AND x15, x14, x24
    and      x28, x25, x26        // AND x28, x25, x26
    addi     x7, x3, -34          // ADDI x7, x3, -34
    slt      x17, x5, x28         // SLT x17, x5, x28
    sltu     x4, x25, x28         // SLTU x4, x25, x28
    subi     x10, x31, 328        // SUBI x10, x31, 328
    ori      x26, x7, -1594       // ORI x26, x7, -1594
    sll      x26, x30, x26        // SLL x26, x30, x26
    addi     x3, x10, -134        // ADDI x3, x10, -134
    xori     x16, x10, -1383      // XORI x16, x10, -1383
    or       x30, x21, x13        // OR x30, x21, x13
    slt      x2, x11, x3          // SLT x2, x11, x3
    addi     x21, x25, -733       // ADDI x21, x25, -733
    addi     x27, x28, 2005       // ADDI x27, x28, 2005
    slti     x8, x4, -1373        // SLTI x8, x4, -1373
    subi     x18, x24, 1515       // SUBI x18, x24, 1515
    slli     x6, x28, 8           // SLLI x6, x28, 8
    add      x28, x10, x9         // ADD x28, x10, x9
    slli     x23, x29, 31         // SLLI x23, x29, 31
    addi     x30, x28, -749       // ADDI x30, x28, -749
    or       x28, x28, x29        // OR x28, x28, x29
    ori      x15, x6, 1797        // ORI x15, x6, 1797
    subi     x10, x26, -2021      // SUBI x10, x26, -2021
    add      x3, x10, x21         // ADD x3, x10, x21
    subi     x10, x10, -2003      // SUBI x10, x10, -2003
    add      x13, x15, x17        // ADD x13, x15, x17
    addi     x14, x21, 398        // ADDI x14, x21, 398
    or       x2, x6, x7           // OR x2, x6, x7
    xori     x15, x15, -923       // XORI x15, x15, -923
    sub      x30, x11, x5         // SUB x30, x11, x5
    sltu     x5, x16, x28         // SLTU x5, x16, x28
    xori     x20, x27, -980       // XORI x20, x27, -980
    subi     x10, x7, 822         // SUBI x10, x7, 822
    sll      x18, x2, x7          // SLL x18, x2, x7
    srai     x12, x10, 0          // SRAI x12, x10, 0
    xori     x1, x5, -149         // XORI x1, x5, -149
    subi     x21, x5, 1962        // SUBI x21, x5, 1962
    slt      x15, x3, x30         // SLT x15, x3, x30
    slti     x25, x26, 1296       // SLTI x25, x26, 1296
    subi     x20, x12, -1012      // SUBI x20, x12, -1012
    and      x28, x20, x27        // AND x28, x20, x27
    sltu     x11, x26, x6         // SLTU x11, x26, x6
    sll      x18, x10, x6         // SLL x18, x10, x6
    and      x26, x15, x18        // AND x26, x15, x18
    addi     x22, x28, -1921      // ADDI x22, x28, -1921
    addi     x11, x20, -1107      // ADDI x11, x20, -1107
    sub      x11, x26, x10        // SUB x11, x26, x10
    slli     x1, x23, 17          // SLLI x1, x23, 17
    sub      x31, x20, x29        // SUB x31, x20, x29
    sltu     x9, x11, x4          // SLTU x9, x11, x4
    srli     x16, x23, 18         // SRLI x16, x23, 18
    addi     x9, x5, -347         // ADDI x9, x5, -347
    addi     x20, x29, 289        // ADDI x20, x29, 289
    slli     x4, x28, 8           // SLLI x4, x28, 8
    subi     x23, x2, -311        // SUBI x23, x2, -311
    sll      x14, x24, x14        // SLL x14, x24, x14
    slti     x4, x3, -352         // SLTI x4, x3, -352
    sub      x28, x21, x15        // SUB x28, x21, x15
    addi     x10, x7, 336         // ADDI x10, x7, 336
    andi     x14, x12, 1914       // ANDI x14, x12, 1914
    add      x25, x6, x29         // ADD x25, x6, x29
    slti     x16, x28, -452       // SLTI x16, x28, -452
    or       x12, x28, x26        // OR x12, x28, x26
    or       x31, x14, x20        // OR x31, x14, x20
    addi     x25, x14, 1220       // ADDI x25, x14, 1220
    addi     x28, x8, -1678       // ADDI x28, x8, -1678
    sub      x16, x25, x14        // SUB x16, x25, x14
    sub      x31, x1, x21         // SUB x31, x1, x21
    add      x5, x1, x18          // ADD x5, x1, x18
    andi     x22, x9, 399         // ANDI x22, x9, 399
    sltu     x8, x17, x15         // SLTU x8, x17, x15
    subi     x24, x9, 29          // SUBI x24, x9, 29
    addi     x3, x14, -1342       // ADDI x3, x14, -1342
    xori     x29, x10, -1688      // XORI x29, x10, -1688
    sub      x12, x22, x22        // SUB x12, x22, x22
    subi     x25, x8, 1627        // SUBI x25, x8, 1627
    subi     x29, x31, -1455      // SUBI x29, x31, -1455
    sll      x8, x7, x4           // SLL x8, x7, x4
    subi     x19, x7, 528         // SUBI x19, x7, 528
    addi     x25, x24, -1966      // ADDI x25, x24, -1966
    add      x22, x8, x15         // ADD x22, x8, x15
    addi     x9, x3, 155          // ADDI x9, x3, 155
    addi     x21, x3, -1092       // ADDI x21, x3, -1092
    addi     x31, x24, -1275      // ADDI x31, x24, -1275
    addi     x7, x13, -1617       // ADDI x7, x13, -1617
    xori     x28, x17, 1354       // XORI x28, x17, 1354
    sll      x5, x19, x9          // SLL x5, x19, x9
    andi     x7, x22, -926        // ANDI x7, x22, -926
    ori      x17, x14, 1143       // ORI x17, x14, 1143
    andi     x19, x12, 924        // ANDI x19, x12, 924
    srli     x31, x16, 15         // SRLI x31, x16, 15
    sltu     x13, x3, x18         // SLTU x13, x3, x18
    andi     x28, x29, 1758       // ANDI x28, x29, 1758
    xori     x31, x1, 1921        // XORI x31, x1, 1921
    sub      x8, x27, x21         // SUB x8, x27, x21
    slli     x19, x30, 13         // SLLI x19, x30, 13
    sltu     x26, x31, x23        // SLTU x26, x31, x23
    add      x24, x19, x28        // ADD x24, x19, x28
    ori      x7, x12, 1931        // ORI x7, x12, 1931
    sltiu    x29, x5, x26         // SLTIU x29, x5, x26
    ori      x2, x6, 1464         // ORI x2, x6, 1464
    addi     x18, x10, 838        // ADDI x18, x10, 838
    sub      x31, x4, x1          // SUB x31, x4, x1
    subi     x24, x21, 781        // SUBI x24, x21, 781
    sub      x14, x7, x22         // SUB x14, x7, x22
    andi     x5, x22, -1880       // ANDI x5, x22, -1880
    andi     x21, x27, -1404      // ANDI x21, x27, -1404
    addi     x15, x9, -1982       // ADDI x15, x9, -1982
    slt      x27, x18, x11        // SLT x27, x18, x11
    ori      x16, x17, -946       // ORI x16, x17, -946
    slt      x30, x19, x2         // SLT x30, x19, x2
    andi     x10, x6, 1120        // ANDI x10, x6, 1120
    sub      x12, x26, x7         // SUB x12, x26, x7
    andi     x6, x23, 1543        // ANDI x6, x23, 1543
    andi     x25, x21, -1386      // ANDI x25, x21, -1386
    or       x3, x14, x8          // OR x3, x14, x8
    subi     x27, x1, 1215        // SUBI x27, x1, 1215
    xori     x15, x25, -1058      // XORI x15, x25, -1058
    addi     x30, x4, 1595        // ADDI x30, x4, 1595
    sub      x27, x19, x18        // SUB x27, x19, x18
    and      x4, x6, x26          // AND x4, x6, x26
    andi     x27, x26, -1281      // ANDI x27, x26, -1281
    or       x31, x28, x2         // OR x31, x28, x2
    add      x28, x20, x10        // ADD x28, x20, x10
    subi     x13, x14, -1585      // SUBI x13, x14, -1585
    slli     x16, x29, 12         // SLLI x16, x29, 12
    sub      x12, x22, x21        // SUB x12, x22, x21
    sltu     x3, x24, x4          // SLTU x3, x24, x4
    subi     x21, x9, -484        // SUBI x21, x9, -484
    ori      x29, x15, 523        // ORI x29, x15, 523
    addi     x2, x21, 879         // ADDI x2, x21, 879
    slt      x26, x8, x11         // SLT x26, x8, x11
    subi     x19, x1, 451         // SUBI x19, x1, 451
    sub      x6, x22, x20         // SUB x6, x22, x20
    subi     x18, x21, -1568      // SUBI x18, x21, -1568
    add      x22, x5, x16         // ADD x22, x5, x16
    srli     x21, x30, 30         // SRLI x21, x30, 30
    andi     x23, x14, 1299       // ANDI x23, x14, 1299
    andi     x1, x22, 1222        // ANDI x1, x22, 1222
    sltiu    x28, x12, x6         // SLTIU x28, x12, x6
    sll      x2, x28, x1          // SLL x2, x28, x1
    sll      x12, x7, x25         // SLL x12, x7, x25
    addi     x4, x10, -732        // ADDI x4, x10, -732
    add      x2, x13, x11         // ADD x2, x13, x11
    addi     x19, x22, 1209       // ADDI x19, x22, 1209
    sub      x22, x14, x23        // SUB x22, x14, x23
    slt      x16, x12, x6         // SLT x16, x12, x6
    add      x7, x25, x16         // ADD x7, x25, x16
    addi     x3, x22, -472        // ADDI x3, x22, -472
    sll      x6, x2, x23          // SLL x6, x2, x23
    sub      x8, x2, x28          // SUB x8, x2, x28
    subi     x21, x30, -1100      // SUBI x21, x30, -1100
    srli     x3, x17, 7           // SRLI x3, x17, 7
    or       x30, x13, x8         // OR x30, x13, x8
    add      x21, x30, x5         // ADD x21, x30, x5
    subi     x2, x3, 157          // SUBI x2, x3, 157
    srli     x8, x7, 9            // SRLI x8, x7, 9
    srli     x15, x18, 31         // SRLI x15, x18, 31
    andi     x8, x7, 1338         // ANDI x8, x7, 1338
    addi     x25, x2, 2017        // ADDI x25, x2, 2017
    addi     x11, x11, -624       // ADDI x11, x11, -624
    addi     x23, x2, 347         // ADDI x23, x2, 347
    addi     x20, x16, -1530      // ADDI x20, x16, -1530
    sll      x24, x31, x25        // SLL x24, x31, x25
    sltiu    x12, x21, x3         // SLTIU x12, x21, x3
    subi     x1, x19, -51         // SUBI x1, x19, -51
    andi     x27, x4, 966         // ANDI x27, x4, 966
    xori     x25, x6, 20          // XORI x25, x6, 20
    sub      x10, x29, x6         // SUB x10, x29, x6
    sub      x9, x22, x1          // SUB x9, x22, x1
    slli     x24, x23, 17         // SLLI x24, x23, 17
    or       x27, x27, x27        // OR x27, x27, x27
    addi     x21, x17, 1576       // ADDI x21, x17, 1576
    addi     x17, x29, 956        // ADDI x17, x29, 956
    add      x16, x14, x19        // ADD x16, x14, x19
    add      x13, x11, x17        // ADD x13, x11, x17
    and      x22, x25, x22        // AND x22, x25, x22
    srli     x15, x19, 21         // SRLI x15, x19, 21
    addi     x4, x28, -1481       // ADDI x4, x28, -1481
    add      x15, x5, x1          // ADD x15, x5, x1
    sltu     x28, x5, x24         // SLTU x28, x5, x24
    andi     x4, x28, -1405       // ANDI x4, x28, -1405
    sltiu    x9, x21, x18         // SLTIU x9, x21, x18
    sub      x27, x27, x10        // SUB x27, x27, x10
    add      x5, x9, x1           // ADD x5, x9, x1
    or       x20, x21, x25        // OR x20, x21, x25
    slti     x7, x23, 1903        // SLTI x7, x23, 1903
    and      x26, x9, x8          // AND x26, x9, x8
    subi     x19, x31, -754       // SUBI x19, x31, -754
    slli     x1, x25, 12          // SLLI x1, x25, 12
    addi     x1, x14, 1640        // ADDI x1, x14, 1640
    srli     x20, x26, 27         // SRLI x20, x26, 27
    xori     x3, x31, -1461       // XORI x3, x31, -1461
    addi     x22, x23, 1688       // ADDI x22, x23, 1688
    xori     x23, x8, 1098        // XORI x23, x8, 1098
    subi     x25, x11, -25        // SUBI x25, x11, -25
    subi     x14, x26, -1970      // SUBI x14, x26, -1970
    sltiu    x23, x16, x14        // SLTIU x23, x16, x14
    addi     x19, x15, -882       // ADDI x19, x15, -882
    sltu     x11, x26, x8         // SLTU x11, x26, x8
    ori      x7, x25, -211        // ORI x7, x25, -211
    add      x16, x8, x10         // ADD x16, x8, x10
    add      x31, x23, x29        // ADD x31, x23, x29
    slt      x18, x31, x23        // SLT x18, x31, x23
    sltiu    x31, x26, x5         // SLTIU x31, x26, x5
    subi     x15, x23, -749       // SUBI x15, x23, -749
    subi     x30, x16, -1810      // SUBI x30, x16, -1810
    srai     x6, x29, 26          // SRAI x6, x29, 26
    addi     x26, x19, -461       // ADDI x26, x19, -461
    add      x30, x16, x26        // ADD x30, x16, x26
    addi     x14, x19, 1445       // ADDI x14, x19, 1445
    subi     x23, x7, -355        // SUBI x23, x7, -355
    slli     x6, x15, 8           // SLLI x6, x15, 8
    addi     x4, x28, 308         // ADDI x4, x28, 308
    and      x14, x3, x28         // AND x14, x3, x28
    slt      x26, x11, x4         // SLT x26, x11, x4
    slli     x9, x24, 31          // SLLI x9, x24, 31
    ori      x24, x13, -905       // ORI x24, x13, -905
    subi     x13, x1, -1361       // SUBI x13, x1, -1361
    xori     x8, x19, -1442       // XORI x8, x19, -1442
    subi     x9, x5, -554         // SUBI x9, x5, -554
    sub      x28, x30, x25        // SUB x28, x30, x25
    sub      x6, x8, x21          // SUB x6, x8, x21
    sll      x3, x1, x19          // SLL x3, x1, x19
    slt      x18, x14, x22        // SLT x18, x14, x22
    sub      x4, x31, x4          // SUB x4, x31, x4
    add      x2, x6, x28          // ADD x2, x6, x28
    sub      x21, x7, x5          // SUB x21, x7, x5
    and      x20, x19, x18        // AND x20, x19, x18
    subi     x16, x24, -679       // SUBI x16, x24, -679
    xori     x25, x31, 785        // XORI x25, x31, 785
    sub      x31, x30, x24        // SUB x31, x30, x24
    subi     x19, x2, -1686       // SUBI x19, x2, -1686
    addi     x29, x18, 1652       // ADDI x29, x18, 1652
    andi     x16, x23, -9         // ANDI x16, x23, -9
    sub      x28, x29, x8         // SUB x28, x29, x8
    sltiu    x11, x28, x10        // SLTIU x11, x28, x10
    and      x22, x9, x1          // AND x22, x9, x1
    sub      x6, x8, x18          // SUB x6, x8, x18
    addi     x27, x22, 1407       // ADDI x27, x22, 1407
    slli     x26, x20, 9          // SLLI x26, x20, 9
    sll      x29, x24, x1         // SLL x29, x24, x1
    add      x9, x7, x20          // ADD x9, x7, x20
    xori     x10, x28, 65         // XORI x10, x28, 65
    ori      x20, x5, -213        // ORI x20, x5, -213
    subi     x8, x5, -379         // SUBI x8, x5, -379
    and      x9, x31, x12         // AND x9, x31, x12
    slti     x30, x25, -1928      // SLTI x30, x25, -1928
    sub      x18, x4, x4          // SUB x18, x4, x4
    add      x2, x31, x19         // ADD x2, x31, x19
    subi     x13, x25, 871        // SUBI x13, x25, 871
    slt      x29, x23, x19        // SLT x29, x23, x19
    or       x6, x18, x12         // OR x6, x18, x12
    sltu     x2, x26, x17         // SLTU x2, x26, x17
    and      x14, x1, x26         // AND x14, x1, x26
    sltiu    x21, x26, x4         // SLTIU x21, x26, x4
    sltiu    x26, x17, x8         // SLTIU x26, x17, x8
    sub      x4, x31, x4          // SUB x4, x31, x4
    xori     x24, x10, -1485      // XORI x24, x10, -1485
    sltu     x15, x16, x9         // SLTU x15, x16, x9
    subi     x24, x15, -1411      // SUBI x24, x15, -1411
    add      x19, x28, x30        // ADD x19, x28, x30
    addi     x12, x22, 372        // ADDI x12, x22, 372
    sub      x3, x30, x5          // SUB x3, x30, x5
    sltiu    x18, x6, x9          // SLTIU x18, x6, x9
    xori     x29, x29, 1015       // XORI x29, x29, 1015
    slt      x22, x1, x31         // SLT x22, x1, x31
    srli     x27, x22, 9          // SRLI x27, x22, 9
    sltu     x14, x2, x19         // SLTU x14, x2, x19
    sub      x26, x16, x24        // SUB x26, x16, x24
    slti     x18, x29, -1069      // SLTI x18, x29, -1069
    and      x9, x25, x20         // AND x9, x25, x20
    ori      x18, x14, -848       // ORI x18, x14, -848
    srai     x30, x24, 7          // SRAI x30, x24, 7
    andi     x5, x22, 1316        // ANDI x5, x22, 1316
    srli     x11, x20, 18         // SRLI x11, x20, 18
    addi     x8, x25, -1193       // ADDI x8, x25, -1193
    sll      x29, x3, x11         // SLL x29, x3, x11
    subi     x22, x18, 1513       // SUBI x22, x18, 1513
    sub      x28, x9, x1          // SUB x28, x9, x1
    sltiu    x1, x30, x5          // SLTIU x1, x30, x5
    ori      x25, x24, 1326       // ORI x25, x24, 1326
    addi     x27, x29, 1961       // ADDI x27, x29, 1961
    andi     x11, x30, 1121       // ANDI x11, x30, 1121
    addi     x30, x17, 1864       // ADDI x30, x17, 1864
    or       x9, x26, x5          // OR x9, x26, x5
    sltu     x21, x3, x16         // SLTU x21, x3, x16
    sub      x21, x19, x30        // SUB x21, x19, x30
    addi     x1, x12, 1270        // ADDI x1, x12, 1270
    subi     x17, x5, -1173       // SUBI x17, x5, -1173
    addi     x7, x20, -1132       // ADDI x7, x20, -1132
    subi     x12, x3, 1145        // SUBI x12, x3, 1145
    add      x6, x6, x2           // ADD x6, x6, x2
    sll      x28, x18, x16        // SLL x28, x18, x16
    subi     x27, x23, -2047      // SUBI x27, x23, -2047
    andi     x19, x15, -1297      // ANDI x19, x15, -1297
    sub      x5, x13, x23         // SUB x5, x13, x23
    addi     x10, x5, -1916       // ADDI x10, x5, -1916
    slti     x30, x13, -470       // SLTI x30, x13, -470
    add      x7, x7, x11          // ADD x7, x7, x11
    and      x21, x6, x8          // AND x21, x6, x8
    addi     x22, x27, 883        // ADDI x22, x27, 883
    sub      x26, x22, x21        // SUB x26, x22, x21
    sltu     x31, x27, x12        // SLTU x31, x27, x12
    xori     x14, x7, -289        // XORI x14, x7, -289
    srai     x10, x20, 10         // SRAI x10, x20, 10
    ori      x10, x20, 1819       // ORI x10, x20, 1819
    addi     x8, x16, -1382       // ADDI x8, x16, -1382
    add      x6, x25, x12         // ADD x6, x25, x12
    sll      x7, x24, x9          // SLL x7, x24, x9
    subi     x26, x17, 1462       // SUBI x26, x17, 1462
    sub      x15, x18, x21        // SUB x15, x18, x21
    subi     x28, x11, 443        // SUBI x28, x11, 443
    subi     x27, x9, -948        // SUBI x27, x9, -948
    subi     x20, x29, -447       // SUBI x20, x29, -447
    and      x21, x3, x30         // AND x21, x3, x30
    addi     x18, x3, 38          // ADDI x18, x3, 38
    sub      x4, x8, x27          // SUB x4, x8, x27
    xori     x6, x14, 2003        // XORI x6, x14, 2003
    sub      x29, x1, x5          // SUB x29, x1, x5
    ori      x19, x7, 202         // ORI x19, x7, 202
    or       x17, x31, x6         // OR x17, x31, x6
    slt      x6, x8, x13          // SLT x6, x8, x13
    xori     x26, x16, -1247      // XORI x26, x16, -1247
    sll      x26, x25, x19        // SLL x26, x25, x19
    slt      x11, x8, x30         // SLT x11, x8, x30
    sll      x6, x12, x18         // SLL x6, x12, x18
    sltu     x24, x2, x22         // SLTU x24, x2, x22
    and      x11, x24, x4         // AND x11, x24, x4
    or       x15, x5, x6          // OR x15, x5, x6
    and      x26, x14, x22        // AND x26, x14, x22
    sub      x11, x1, x8          // SUB x11, x1, x8
    slli     x9, x30, 3           // SLLI x9, x30, 3
    slt      x26, x2, x22         // SLT x26, x2, x22
    srai     x13, x20, 16         // SRAI x13, x20, 16
    add      x14, x9, x27         // ADD x14, x9, x27
    srai     x8, x24, 5           // SRAI x8, x24, 5
    slti     x4, x27, 1819        // SLTI x4, x27, 1819
    or       x16, x10, x6         // OR x16, x10, x6
    xori     x18, x25, -1220      // XORI x18, x25, -1220
    ori      x25, x10, -1265      // ORI x25, x10, -1265
    xori     x7, x20, 1548        // XORI x7, x20, 1548
    addi     x8, x10, 674         // ADDI x8, x10, 674
    addi     x30, x3, 133         // ADDI x30, x3, 133
    sll      x9, x4, x12          // SLL x9, x4, x12
    andi     x4, x27, -638        // ANDI x4, x27, -638
    addi     x21, x26, 1465       // ADDI x21, x26, 1465
    sub      x6, x21, x26         // SUB x6, x21, x26
    or       x27, x18, x20        // OR x27, x18, x20
    add      x14, x19, x25        // ADD x14, x19, x25
    ori      x6, x3, -186         // ORI x6, x3, -186
    andi     x14, x7, 1609        // ANDI x14, x7, 1609
    ori      x15, x11, -994       // ORI x15, x11, -994
    xori     x17, x13, -1546      // XORI x17, x13, -1546
    srli     x18, x18, 4          // SRLI x18, x18, 4
    addi     x11, x5, -938        // ADDI x11, x5, -938
    subi     x18, x3, -548        // SUBI x18, x3, -548
    slli     x6, x19, 26          // SLLI x6, x19, 26
    slti     x10, x28, 190        // SLTI x10, x28, 190
    add      x3, x24, x6          // ADD x3, x24, x6
    add      x17, x16, x16        // ADD x17, x16, x16
    add      x22, x8, x12         // ADD x22, x8, x12
    addi     x1, x30, -652        // ADDI x1, x30, -652
    addi     x3, x30, -1326       // ADDI x3, x30, -1326
    ori      x10, x18, 1768       // ORI x10, x18, 1768

    # Random Test Cases
    xor      x13, x18, x13        // XOR x13, x18, x13
    lui      x13, 782345          // LUI x13, 782345
    srl      x9, x11, x2          // SRL x9, x11, x2
    sra      x9, x4, x4           // SRA x9, x4, x4
    auipc    x7, 893472           // AUIPC x7, 893472
    xor      x15, x21, x28        // XOR x15, x21, x28
    auipc    x24, 468096          // AUIPC x24, 468096
    lui      x14, 527319          // LUI x14, 527319
    auipc    x15, 627561          // AUIPC x15, 627561
    srl      x21, x1, x26         // SRL x21, x1, x26
    auipc    x20, 278863          // AUIPC x20, 278863
    auipc    x23, 903738          // AUIPC x23, 903738
    srl      x28, x17, x7         // SRL x28, x17, x7
    lui      x22, 685930          // LUI x22, 685930
    xor      x25, x7, x24         // XOR x25, x7, x24
    auipc    x25, 381695          // AUIPC x25, 381695
    lui      x27, 39500           // LUI x27, 39500
    auipc    x9, 308130           // AUIPC x9, 308130
    srl      x6, x20, x4          // SRL x6, x20, x4
    srl      x19, x30, x7         // SRL x19, x30, x7
    lui      x12, 432557          // LUI x12, 432557
    lui      x7, 121932           // LUI x7, 121932
    lui      x30, 1020571         // LUI x30, 1020571
    sra      x13, x9, x14         // SRA x13, x9, x14
    xor      x6, x6, x31          // XOR x6, x6, x31
    lui      x25, 100481          // LUI x25, 100481
    xor      x21, x28, x6         // XOR x21, x28, x6
    auipc    x17, 869141          // AUIPC x17, 869141
    lui      x31, 556487          // LUI x31, 556487
    lui      x15, 1016964         // LUI x15, 1016964
    lui      x30, 967778          // LUI x30, 967778
    lui      x8, 1004931          // LUI x8, 1004931
    xor      x2, x4, x23          // XOR x2, x4, x23
    xor      x13, x16, x24        // XOR x13, x16, x24
    auipc    x29, 957552          // AUIPC x29, 957552
    auipc    x14, 733892          // AUIPC x14, 733892
    xor      x24, x5, x12         // XOR x24, x5, x12
    auipc    x7, 289301           // AUIPC x7, 289301
    srl      x6, x27, x15         // SRL x6, x27, x15
    lui      x19, 910441          // LUI x19, 910441
    auipc    x15, 894853          // AUIPC x15, 894853
    auipc    x21, 841371          // AUIPC x21, 841371
    lui      x11, 315763          // LUI x11, 315763
    sra      x24, x9, x25         // SRA x24, x9, x25
    lui      x15, 94016           // LUI x15, 94016
    lui      x17, 662984          // LUI x17, 662984
    srl      x26, x16, x21        // SRL x26, x16, x21
    xor      x4, x20, x23         // XOR x4, x20, x23
    srl      x17, x25, x5         // SRL x17, x25, x5
    sra      x31, x20, x20        // SRA x31, x20, x20
    xor      x16, x24, x26        // XOR x16, x24, x26
    lui      x23, 1021532         // LUI x23, 1021532
    xor      x21, x24, x20        // XOR x21, x24, x20
    xor      x1, x22, x3          // XOR x1, x22, x3
    xor      x30, x20, x4         // XOR x30, x20, x4
    srl      x31, x23, x28        // SRL x31, x23, x28
    auipc    x19, 771486          // AUIPC x19, 771486
    lui      x17, 268010          // LUI x17, 268010
    auipc    x17, 837615          // AUIPC x17, 837615
    sra      x29, x10, x6         // SRA x29, x10, x6
    auipc    x1, 197600           // AUIPC x1, 197600
    lui      x23, 299934          // LUI x23, 299934
    auipc    x9, 674943           // AUIPC x9, 674943
    auipc    x9, 706905           // AUIPC x9, 706905
    xor      x28, x1, x26         // XOR x28, x1, x26
    sra      x28, x20, x6         // SRA x28, x20, x6
    auipc    x25, 451464          // AUIPC x25, 451464
    srl      x9, x12, x17         // SRL x9, x12, x17
    lui      x31, 372665          // LUI x31, 372665
    xor      x18, x6, x4          // XOR x18, x6, x4
    auipc    x24, 613985          // AUIPC x24, 613985
    lui      x31, 286285          // LUI x31, 286285
    auipc    x14, 893893          // AUIPC x14, 893893
    auipc    x23, 887749          // AUIPC x23, 887749
    sra      x21, x18, x30        // SRA x21, x18, x30
    auipc    x27, 504357          // AUIPC x27, 504357
    auipc    x1, 362612           // AUIPC x1, 362612
    srl      x31, x28, x11        // SRL x31, x28, x11
    xor      x20, x14, x21        // XOR x20, x14, x21
    srl      x21, x5, x29         // SRL x21, x5, x29
    auipc    x2, 72385            // AUIPC x2, 72385
    xor      x5, x1, x16          // XOR x5, x1, x16
    xor      x2, x25, x4          // XOR x2, x25, x4
    xor      x27, x20, x19        // XOR x27, x20, x19
    auipc    x24, 765106          // AUIPC x24, 765106
    auipc    x23, 724409          // AUIPC x23, 724409
    srl      x14, x2, x20         // SRL x14, x2, x20
    sra      x9, x8, x9           // SRA x9, x8, x9
    xor      x2, x9, x30          // XOR x2, x9, x30
    srl      x1, x23, x2          // SRL x1, x23, x2

    # Program termination
    addi    x1, x0, 93      // sys_exit
    addi    x10, x0, 0      // exit status
    ecall                   // system call
