# CV32E40P ALU Test Assembly Program
# Generated by asm_generator.py
# Copyright 2024 ChipAgents

.section .text
.global _start

_start:
    # Directed Test Cases
    add      x1, x0, x0           // ADD x1, zero, zero (result = 0)
    add      x2, x1, x1           // ADD x2, x1, x1 (double)
    sub      x3, x2, x1           // SUB x3, x2, x1
    addi     x4, x0, 2147483647   // ADDI x4, zero, MAX_INT
    addi     x5, x0, -2147483648  // ADDI x5, zero, MIN_INT
    andi     x6, x4, -1           // ANDI x6, x4, 0xFFFFFFFF
    ori      x7, x0, 1431655765   // ORI x7, zero, 0x55555555
    xori     x8, x7, -1431655766  // XORI x8, x7, 0xAAAAAAAA
    and      x9, x7, x8           // AND x9, x7, x8 (should be 0)
    or       x10, x7, x8          // OR x10, x7, x8 (should be 0xFFFFFFFF)
    slli     x11, x4, 1           // SLLI x11, x4, 1 (left shift by 1)
    srli     x12, x4, 1           // SRLI x12, x4, 1 (logical right shift)
    srai     x13, x5, 1           // SRAI x13, x5, 1 (arithmetic right shift)
    sll      x14, x4, x1          // SLL x14, x4, x1 (variable shift)
    slt      x15, x5, x4          // SLT x15, MIN_INT, MAX_INT (should be 1)
    sltu     x16, x4, x5          // SLTU x16, MAX_INT, MIN_INT (unsigned)
    slti     x17, x4, 0           // SLTI x17, MAX_INT, 0
    sltiu    x18, x0, 1           // SLTIU x18, zero, 1
    and      x27, x27, x26        // AND x27, x27, x26
    ori      x21, x6, -518        // ORI x21, x6, -518
    xori     x3, x17, 1328        // XORI x3, x17, 1328
    addi     x11, x1, -1828       // ADDI x11, x1, -1828
    sltu     x10, x4, x21         // SLTU x10, x4, x21
    xori     x19, x6, -143        // XORI x19, x6, -143
    sltu     x24, x26, x25        // SLTU x24, x26, x25
    or       x2, x6, x10          // OR x2, x6, x10
    or       x13, x11, x1         // OR x13, x11, x1
    subi     x3, x13, -578        // SUBI x3, x13, -578
    srai     x12, x7, 7           // SRAI x12, x7, 7
    and      x1, x21, x16         // AND x1, x21, x16
    ori      x31, x14, -397       // ORI x31, x14, -397
    xori     x23, x4, -1393       // XORI x23, x4, -1393
    sub      x18, x3, x17         // SUB x18, x3, x17
    slt      x9, x17, x25         // SLT x9, x17, x25
    andi     x14, x6, -1          // ANDI x14, x6, -1
    addi     x6, x13, 1           // ADDI x6, x13, 1
    srli     x29, x8, 26          // SRLI x29, x8, 26
    andi     x11, x4, 240         // ANDI x11, x4, 240
    srai     x20, x19, 12         // SRAI x20, x19, 12
    srli     x29, x8, 21          // SRLI x29, x8, 21
    sll      x9, x25, x14         // SLL x9, x25, x14
    add      x21, x25, x3         // ADD x21, x25, x3
    add      x9, x24, x15         // ADD x9, x24, x15
    slli     x10, x15, 16         // SLLI x10, x15, 16
    andi     x16, x2, 0           // ANDI x16, x2, 0
    or       x30, x1, x22         // OR x30, x1, x22
    subi     x16, x6, 2047        // SUBI x16, x6, 2047
    slti     x28, x13, -2048      // SLTI x28, x13, -2048
    and      x14, x7, x6          // AND x14, x7, x6
    addi     x8, x11, -1935       // ADDI x8, x11, -1935
    add      x26, x11, x13        // ADD x26, x11, x13
    and      x8, x4, x16          // AND x8, x4, x16
    sub      x9, x19, x18         // SUB x9, x19, x18
    xori     x10, x2, -1297       // XORI x10, x2, -1297
    sub      x18, x17, x22        // SUB x18, x17, x22
    add      x28, x13, x12        // ADD x28, x13, x12
    srli     x22, x20, 1          // SRLI x22, x20, 1
    andi     x2, x11, 397         // ANDI x2, x11, 397
    add      x19, x4, x16         // ADD x19, x4, x16
    or       x17, x4, x15         // OR x17, x4, x15
    and      x14, x8, x29         // AND x14, x8, x29
    xori     x26, x6, -69         // XORI x26, x6, -69
    srli     x21, x7, 10          // SRLI x21, x7, 10
    slli     x28, x25, 0          // SLLI x28, x25, 0
    sll      x26, x29, x25        // SLL x26, x29, x25
    add      x4, x9, x19          // ADD x4, x9, x19
    slli     x22, x13, 15         // SLLI x22, x13, 15
    srli     x4, x17, 1           // SRLI x4, x17, 1
    ori      x30, x22, 1226       // ORI x30, x22, 1226
    and      x14, x15, x4         // AND x14, x15, x4
    andi     x10, x14, -646       // ANDI x10, x14, -646
    ori      x30, x13, 16         // ORI x30, x13, 16
    ori      x9, x8, 2047         // ORI x9, x8, 2047
    ori      x1, x1, 1            // ORI x1, x1, 1
    srli     x10, x17, 18         // SRLI x10, x17, 18
    subi     x13, x30, 1241       // SUBI x13, x30, 1241
    srai     x24, x22, 28         // SRAI x24, x22, 28
    subi     x28, x23, -749       // SUBI x28, x23, -749
    slt      x23, x4, x24         // SLT x23, x4, x24
    slt      x9, x22, x11         // SLT x9, x22, x11
    sltiu    x16, x3, x13         // SLTIU x16, x3, x13
    sll      x24, x14, x8         // SLL x24, x14, x8
    xori     x9, x30, -1          // XORI x9, x30, -1
    xori     x20, x11, 853        // XORI x20, x11, 853
    ori      x28, x15, 16         // ORI x28, x15, 16
    or       x20, x25, x25        // OR x20, x25, x25
    xori     x27, x19, 398        // XORI x27, x19, 398
    addi     x8, x14, -202        // ADDI x8, x14, -202
    add      x25, x23, x22        // ADD x25, x23, x22
    slt      x25, x13, x5         // SLT x25, x13, x5
    or       x22, x7, x1          // OR x22, x7, x1
    addi     x19, x8, 220         // ADDI x19, x8, 220
    slti     x12, x11, -1057      // SLTI x12, x11, -1057
    slli     x21, x11, 15         // SLLI x21, x11, 15
    or       x22, x10, x22        // OR x22, x10, x22
    sub      x5, x17, x7          // SUB x5, x17, x7
    and      x30, x23, x30        // AND x30, x23, x30
    sub      x23, x31, x2         // SUB x23, x31, x2
    ori      x14, x1, -1          // ORI x14, x1, -1
    srli     x5, x16, 6           // SRLI x5, x16, 6
    and      x24, x5, x1          // AND x24, x5, x1
    addi     x5, x30, -313        // ADDI x5, x30, -313
    ori      x11, x13, -1         // ORI x11, x13, -1
    ori      x6, x18, 1103        // ORI x6, x18, 1103
    sub      x29, x29, x9         // SUB x29, x29, x9
    sub      x18, x24, x20        // SUB x18, x24, x20
    xori     x9, x10, 971         // XORI x9, x10, 971
    srli     x7, x13, 6           // SRLI x7, x13, 6
    slt      x21, x18, x6         // SLT x21, x18, x6
    ori      x6, x3, -1155        // ORI x6, x3, -1155
    slli     x5, x31, 2           // SLLI x5, x31, 2
    and      x13, x9, x10         // AND x13, x9, x10
    sub      x26, x30, x24        // SUB x26, x30, x24
    add      x14, x5, x9          // ADD x14, x5, x9
    and      x22, x11, x22        // AND x22, x11, x22
    xori     x19, x26, 1365       // XORI x19, x26, 1365
    and      x10, x29, x29        // AND x10, x29, x29
    srli     x14, x15, 26         // SRLI x14, x15, 26
    and      x16, x16, x8         // AND x16, x16, x8
    sub      x21, x1, x27         // SUB x21, x1, x27
    sltu     x1, x30, x31         // SLTU x1, x30, x31
    sll      x9, x4, x27          // SLL x9, x4, x27
    and      x16, x20, x19        // AND x16, x20, x19
    xori     x3, x1, 819          // XORI x3, x1, 819
    subi     x3, x3, -771         // SUBI x3, x3, -771
    andi     x24, x22, 15         // ANDI x24, x22, 15
    or       x14, x28, x5         // OR x14, x28, x5
    and      x15, x12, x4         // AND x15, x12, x4
    addi     x3, x17, 1           // ADDI x3, x17, 1
    subi     x8, x29, 256         // SUBI x8, x29, 256
    and      x7, x19, x15         // AND x7, x19, x15
    andi     x2, x6, -1254        // ANDI x2, x6, -1254
    and      x10, x25, x2         // AND x10, x25, x2
    ori      x27, x21, 15         // ORI x27, x21, 15
    or       x29, x2, x3          // OR x29, x2, x3
    sub      x15, x31, x31        // SUB x15, x31, x31
    sll      x11, x28, x14        // SLL x11, x28, x14
    xori     x11, x14, 2047       // XORI x11, x14, 2047
    xori     x25, x19, 724        // XORI x25, x19, 724
    ori      x26, x10, 844        // ORI x26, x10, 844
    sltiu    x26, x31, x15        // SLTIU x26, x31, x15
    srli     x7, x14, 14          // SRLI x7, x14, 14
    andi     x31, x17, 0          // ANDI x31, x17, 0
    srai     x22, x30, 28         // SRAI x22, x30, 28
    sll      x31, x26, x22        // SLL x31, x26, x22
    and      x5, x12, x19         // AND x5, x12, x19
    slt      x7, x26, x1          // SLT x7, x26, x1
    andi     x17, x21, 256        // ANDI x17, x21, 256
    slti     x27, x11, -43        // SLTI x27, x11, -43
    slli     x29, x27, 0          // SLLI x29, x27, 0
    ori      x27, x8, 1584        // ORI x27, x8, 1584
    sll      x31, x31, x23        // SLL x31, x31, x23
    slli     x5, x5, 29           // SLLI x5, x5, 29
    sub      x5, x28, x4          // SUB x5, x28, x4
    sll      x11, x20, x14        // SLL x11, x20, x14
    andi     x3, x14, 2047        // ANDI x3, x14, 2047
    sub      x18, x12, x4         // SUB x18, x12, x4
    sll      x21, x9, x5          // SLL x21, x9, x5
    or       x17, x28, x19        // OR x17, x28, x19
    and      x29, x11, x28        // AND x29, x11, x28
    srli     x22, x18, 1          // SRLI x22, x18, 1
    srli     x23, x25, 15         // SRLI x23, x25, 15
    sub      x25, x8, x12         // SUB x25, x8, x12
    slli     x15, x2, 2           // SLLI x15, x2, 2
    srli     x3, x19, 5           // SRLI x3, x19, 5
    xori     x10, x5, 1           // XORI x10, x5, 1
    sltu     x25, x29, x28        // SLTU x25, x29, x28
    or       x14, x29, x12        // OR x14, x29, x12
    sltiu    x24, x29, x16        // SLTIU x24, x29, x16
    sub      x14, x28, x31        // SUB x14, x28, x31
    add      x20, x11, x24        // ADD x20, x11, x24
    and      x22, x11, x14        // AND x22, x11, x14
    and      x29, x9, x11         // AND x29, x9, x11
    sltu     x18, x23, x1         // SLTU x18, x23, x1
    addi     x13, x30, -1297      // ADDI x13, x30, -1297
    ori      x3, x31, -1149       // ORI x3, x31, -1149
    slli     x3, x22, 6           // SLLI x3, x22, 6
    sltu     x30, x2, x29         // SLTU x30, x2, x29
    xori     x23, x28, -318       // XORI x23, x28, -318
    srli     x4, x21, 25          // SRLI x4, x21, 25
    addi     x27, x23, 275        // ADDI x27, x23, 275
    sll      x1, x11, x11         // SLL x1, x11, x11
    and      x9, x12, x30         // AND x9, x12, x30
    slli     x14, x30, 30         // SLLI x14, x30, 30
    add      x31, x3, x17         // ADD x31, x3, x17
    sll      x29, x13, x25        // SLL x29, x13, x25
    and      x21, x12, x24        // AND x21, x12, x24
    ori      x31, x12, 646        // ORI x31, x12, 646
    and      x20, x17, x11        // AND x20, x17, x11
    sub      x14, x18, x22        // SUB x14, x18, x22
    addi     x26, x31, 408        // ADDI x26, x31, 408
    sub      x2, x13, x28         // SUB x2, x13, x28
    xori     x6, x20, -1338       // XORI x6, x20, -1338
    sll      x24, x8, x17         // SLL x24, x8, x17
    xori     x13, x1, 1124        // XORI x13, x1, 1124
    add      x21, x24, x28        // ADD x21, x24, x28
    sub      x1, x31, x22         // SUB x1, x31, x22
    subi     x21, x27, 1412       // SUBI x21, x27, 1412
    subi     x26, x15, 1753       // SUBI x26, x15, 1753
    srli     x30, x13, 26         // SRLI x30, x13, 26
    srai     x3, x1, 21           // SRAI x3, x1, 21
    slti     x26, x9, -929        // SLTI x26, x9, -929
    xori     x23, x14, 93         // XORI x23, x14, 93
    sltiu    x9, x9, x26          // SLTIU x9, x9, x26
    ori      x18, x17, 315        // ORI x18, x17, 315
    sub      x8, x6, x28          // SUB x8, x6, x28
    sll      x12, x7, x8          // SLL x12, x7, x8
    or       x30, x12, x26        // OR x30, x12, x26
    addi     x28, x23, 16         // ADDI x28, x23, 16
    subi     x3, x6, -472         // SUBI x3, x6, -472
    srai     x24, x18, 19         // SRAI x24, x18, 19
    or       x18, x15, x28        // OR x18, x15, x28
    sltu     x28, x2, x3          // SLTU x28, x2, x3
    srli     x6, x11, 20          // SRLI x6, x11, 20
    sll      x3, x23, x27         // SLL x3, x23, x27
    or       x15, x10, x28        // OR x15, x10, x28
    slt      x22, x13, x18        // SLT x22, x13, x18
    slt      x23, x9, x20         // SLT x23, x9, x20
    slli     x6, x2, 2            // SLLI x6, x2, 2
    ori      x13, x18, 271        // ORI x13, x18, 271
    subi     x22, x29, 1365       // SUBI x22, x29, 1365
    slt      x17, x26, x30        // SLT x17, x26, x30
    srai     x13, x23, 4          // SRAI x13, x23, 4
    or       x12, x5, x2          // OR x12, x5, x2
    xori     x26, x30, -1607      // XORI x26, x30, -1607
    slti     x12, x19, 2047       // SLTI x12, x19, 2047
    add      x14, x2, x1          // ADD x14, x2, x1
    or       x8, x6, x9           // OR x8, x6, x9
    sub      x11, x15, x21        // SUB x11, x15, x21
    srli     x2, x24, 3           // SRLI x2, x24, 3
    addi     x15, x17, -1         // ADDI x15, x17, -1
    slt      x3, x19, x20         // SLT x3, x19, x20
    add      x13, x4, x22         // ADD x13, x4, x22
    sub      x26, x2, x4          // SUB x26, x2, x4
    sltiu    x26, x22, x14        // SLTIU x26, x22, x14
    sltu     x31, x1, x30         // SLTU x31, x1, x30
    sll      x30, x19, x18        // SLL x30, x19, x18
    and      x15, x11, x29        // AND x15, x11, x29
    srli     x11, x30, 11         // SRLI x11, x30, 11
    srai     x2, x16, 18          // SRAI x2, x16, 18
    and      x15, x24, x24        // AND x15, x24, x24
    addi     x8, x22, -833        // ADDI x8, x22, -833
    xori     x28, x9, -844        // XORI x28, x9, -844
    srai     x8, x9, 26           // SRAI x8, x9, 26
    slli     x12, x3, 1           // SLLI x12, x3, 1
    subi     x9, x21, 256         // SUBI x9, x21, 256
    ori      x28, x21, -963       // ORI x28, x21, -963
    add      x7, x27, x7          // ADD x7, x27, x7
    sll      x18, x29, x14        // SLL x18, x29, x14
    sub      x12, x23, x19        // SUB x12, x23, x19
    sll      x25, x8, x31         // SLL x25, x8, x31
    srai     x5, x30, 12          // SRAI x5, x30, 12
    srai     x25, x27, 14         // SRAI x25, x27, 14
    srli     x30, x2, 26          // SRLI x30, x2, 26
    slli     x29, x5, 13          // SLLI x29, x5, 13
    subi     x19, x10, -557       // SUBI x19, x10, -557
    sub      x26, x25, x23        // SUB x26, x25, x23
    slti     x18, x9, 2047        // SLTI x18, x9, 2047
    slli     x7, x15, 6           // SLLI x7, x15, 6
    sub      x27, x8, x28         // SUB x27, x8, x28
    sub      x12, x28, x6         // SUB x12, x28, x6
    andi     x4, x10, 1475        // ANDI x4, x10, 1475
    sltiu    x7, x15, x17         // SLTIU x7, x15, x17
    sltiu    x31, x27, x28        // SLTIU x31, x27, x28
    sll      x19, x2, x24         // SLL x19, x2, x24
    addi     x6, x29, 1365        // ADDI x6, x29, 1365
    sub      x30, x1, x23         // SUB x30, x1, x23
    srli     x23, x6, 9           // SRLI x23, x6, 9
    or       x25, x1, x1          // OR x25, x1, x1
    or       x23, x14, x10        // OR x23, x14, x10
    ori      x24, x7, 1675        // ORI x24, x7, 1675
    xori     x19, x5, 364         // XORI x19, x5, 364
    sltu     x5, x14, x20         // SLTU x5, x14, x20
    and      x1, x3, x15          // AND x1, x3, x15
    and      x4, x7, x22          // AND x4, x7, x22
    ori      x13, x23, -1423      // ORI x13, x23, -1423
    ori      x3, x29, 2047        // ORI x3, x29, 2047
    andi     x5, x12, 1           // ANDI x5, x12, 1
    sltiu    x2, x10, x19         // SLTIU x2, x10, x19
    srai     x9, x4, 28           // SRAI x9, x4, 28
    ori      x20, x7, -2048       // ORI x20, x7, -2048
    and      x25, x10, x9         // AND x25, x10, x9
    sltiu    x11, x1, x23         // SLTIU x11, x1, x23
    and      x1, x9, x15          // AND x1, x9, x15
    slli     x8, x14, 17          // SLLI x8, x14, 17
    srai     x16, x27, 17         // SRAI x16, x27, 17
    subi     x3, x1, -1005        // SUBI x3, x1, -1005
    srai     x4, x20, 5           // SRAI x4, x20, 5
    xori     x28, x17, -1094      // XORI x28, x17, -1094
    andi     x3, x18, 1738        // ANDI x3, x18, 1738
    slti     x29, x14, -1266      // SLTI x29, x14, -1266
    and      x18, x25, x14        // AND x18, x25, x14
    subi     x8, x2, -395         // SUBI x8, x2, -395
    sll      x11, x29, x15        // SLL x11, x29, x15
    add      x14, x28, x20        // ADD x14, x28, x20
    ori      x20, x2, -1          // ORI x20, x2, -1
    addi     x14, x23, 520        // ADDI x14, x23, 520
    addi     x17, x15, -1         // ADDI x17, x15, -1
    ori      x11, x8, 0           // ORI x11, x8, 0
    sll      x23, x17, x6         // SLL x23, x17, x6
    ori      x3, x29, -1501       // ORI x3, x29, -1501
    subi     x21, x29, -1705      // SUBI x21, x29, -1705
    sll      x18, x9, x25         // SLL x18, x9, x25
    sll      x10, x14, x23        // SLL x10, x14, x23
    or       x16, x11, x31        // OR x16, x11, x31
    srli     x17, x27, 13         // SRLI x17, x27, 13
    or       x12, x19, x8         // OR x12, x19, x8
    sll      x31, x8, x31         // SLL x31, x8, x31
    sltiu    x9, x24, x26         // SLTIU x9, x24, x26
    slti     x31, x29, -1859      // SLTI x31, x29, -1859
    srli     x15, x27, 20         // SRLI x15, x27, 20
    sltu     x22, x18, x10        // SLTU x22, x18, x10
    or       x13, x14, x24        // OR x13, x14, x24
    sltu     x6, x18, x21         // SLTU x6, x18, x21
    or       x23, x14, x10        // OR x23, x14, x10
    xori     x28, x8, -1666       // XORI x28, x8, -1666
    xori     x13, x2, 1215        // XORI x13, x2, 1215
    xori     x5, x11, -330        // XORI x5, x11, -330
    slli     x23, x28, 23         // SLLI x23, x28, 23
    sub      x28, x31, x7         // SUB x28, x31, x7
    ori      x1, x10, 1           // ORI x1, x10, 1
    andi     x29, x4, -1200       // ANDI x29, x4, -1200
    slli     x4, x13, 5           // SLLI x4, x13, 5
    srai     x5, x22, 20          // SRAI x5, x22, 20
    xori     x21, x10, 0          // XORI x21, x10, 0
    sub      x16, x2, x31         // SUB x16, x2, x31
    xori     x18, x3, -923        // XORI x18, x3, -923
    add      x12, x24, x3         // ADD x12, x24, x3
    sll      x9, x22, x24         // SLL x9, x22, x24
    add      x25, x27, x27        // ADD x25, x27, x27
    subi     x21, x14, -1165      // SUBI x21, x14, -1165
    add      x23, x15, x26        // ADD x23, x15, x26
    sltu     x8, x28, x25         // SLTU x8, x28, x25
    ori      x19, x15, 253        // ORI x19, x15, 253
    add      x11, x28, x10        // ADD x11, x28, x10
    add      x20, x25, x15        // ADD x20, x25, x15
    addi     x29, x13, 256        // ADDI x29, x13, 256
    sub      x15, x5, x17         // SUB x15, x5, x17
    slt      x22, x15, x6         // SLT x22, x15, x6
    xori     x14, x4, -1396       // XORI x14, x4, -1396
    sltu     x19, x16, x9         // SLTU x19, x16, x9
    and      x10, x16, x24        // AND x10, x16, x24
    subi     x3, x29, 1           // SUBI x3, x29, 1
    srai     x14, x12, 29         // SRAI x14, x12, 29
    and      x6, x11, x5          // AND x6, x11, x5
    add      x1, x28, x8          // ADD x1, x28, x8
    slt      x7, x8, x24          // SLT x7, x8, x24
    srli     x17, x15, 6          // SRLI x17, x15, 6
    srai     x3, x25, 31          // SRAI x3, x25, 31
    xori     x27, x10, -1787      // XORI x27, x10, -1787
    srai     x17, x24, 12         // SRAI x17, x24, 12
    slli     x28, x5, 29          // SLLI x28, x5, 29
    and      x30, x12, x27        // AND x30, x12, x27
    addi     x30, x15, 352        // ADDI x30, x15, 352
    addi     x30, x30, -1432      // ADDI x30, x30, -1432
    subi     x12, x17, 819        // SUBI x12, x17, 819
    or       x26, x13, x16        // OR x26, x13, x16
    addi     x12, x27, -1799      // ADDI x12, x27, -1799
    ori      x22, x17, -1748      // ORI x22, x17, -1748
    slli     x17, x28, 19         // SLLI x17, x28, 19
    ori      x7, x12, -131        // ORI x7, x12, -131
    add      x26, x15, x4         // ADD x26, x15, x4
    add      x2, x26, x2          // ADD x2, x26, x2
    andi     x25, x3, 256         // ANDI x25, x3, 256
    sltiu    x6, x16, x15         // SLTIU x6, x16, x15
    sltu     x9, x13, x27         // SLTU x9, x13, x27
    sll      x4, x25, x20         // SLL x4, x25, x20
    sltiu    x14, x25, x22        // SLTIU x14, x25, x22
    srli     x28, x13, 0          // SRLI x28, x13, 0
    addi     x24, x16, -1610      // ADDI x24, x16, -1610
    slli     x1, x19, 15          // SLLI x1, x19, 15
    sub      x19, x4, x7          // SUB x19, x4, x7
    or       x2, x16, x14         // OR x2, x16, x14
    slli     x12, x5, 24          // SLLI x12, x5, 24
    andi     x26, x21, -182       // ANDI x26, x21, -182
    sll      x23, x4, x7          // SLL x23, x4, x7
    sll      x28, x2, x11         // SLL x28, x2, x11
    srai     x16, x29, 20         // SRAI x16, x29, 20
    sub      x22, x31, x30        // SUB x22, x31, x30
    sll      x6, x10, x10         // SLL x6, x10, x10
    subi     x3, x19, -299        // SUBI x3, x19, -299
    and      x26, x20, x11        // AND x26, x20, x11
    sltu     x6, x17, x23         // SLTU x6, x17, x23
    andi     x3, x27, 1022        // ANDI x3, x27, 1022
    slli     x20, x30, 28         // SLLI x20, x30, 28
    sll      x16, x28, x22        // SLL x16, x28, x22
    slli     x24, x17, 23         // SLLI x24, x17, 23
    add      x30, x21, x25        // ADD x30, x21, x25
    subi     x1, x31, -430        // SUBI x1, x31, -430
    andi     x9, x20, 1           // ANDI x9, x20, 1
    sub      x1, x16, x19         // SUB x1, x16, x19
    andi     x15, x16, -31        // ANDI x15, x16, -31
    xori     x31, x15, -1288      // XORI x31, x15, -1288
    andi     x2, x2, 1280         // ANDI x2, x2, 1280
    sltu     x9, x4, x16          // SLTU x9, x4, x16
    srai     x26, x9, 19          // SRAI x26, x9, 19
    sub      x3, x12, x5          // SUB x3, x12, x5
    addi     x31, x2, 733         // ADDI x31, x2, 733
    ori      x31, x25, 697        // ORI x31, x25, 697
    subi     x14, x23, -1820      // SUBI x14, x23, -1820
    slti     x11, x4, -204        // SLTI x11, x4, -204
    andi     x10, x22, -1489      // ANDI x10, x22, -1489
    and      x31, x25, x12        // AND x31, x25, x12
    sll      x15, x3, x6          // SLL x15, x3, x6
    ori      x28, x22, -1021      // ORI x28, x22, -1021
    xori     x5, x2, 819          // XORI x5, x2, 819
    and      x1, x29, x9          // AND x1, x29, x9
    sll      x15, x10, x19        // SLL x15, x10, x19
    slli     x13, x24, 15         // SLLI x13, x24, 15
    addi     x6, x1, -1536        // ADDI x6, x1, -1536
    slli     x8, x3, 13           // SLLI x8, x3, 13
    sub      x15, x14, x22        // SUB x15, x14, x22
    subi     x13, x28, -2048      // SUBI x13, x28, -2048
    slt      x12, x6, x24         // SLT x12, x6, x24
    ori      x4, x10, -2048       // ORI x4, x10, -2048
    addi     x14, x1, 1738        // ADDI x14, x1, 1738
    ori      x25, x21, 256        // ORI x25, x21, 256
    xori     x28, x6, 1365        // XORI x28, x6, 1365
    srli     x30, x13, 21         // SRLI x30, x13, 21
    addi     x29, x4, 16          // ADDI x29, x4, 16
    add      x15, x5, x21         // ADD x15, x5, x21
    subi     x29, x5, 783         // SUBI x29, x5, 783
    ori      x29, x15, 1053       // ORI x29, x15, 1053
    subi     x10, x26, -1241      // SUBI x10, x26, -1241
    srli     x13, x3, 21          // SRLI x13, x3, 21
    sub      x3, x8, x26          // SUB x3, x8, x26
    xori     x11, x14, -1231      // XORI x11, x14, -1231
    srai     x25, x29, 28         // SRAI x25, x29, 28
    slt      x6, x14, x6          // SLT x6, x14, x6
    srai     x20, x29, 31         // SRAI x20, x29, 31
    andi     x12, x29, -223       // ANDI x12, x29, -223
    subi     x8, x6, -1479        // SUBI x8, x6, -1479
    xori     x20, x21, 982        // XORI x20, x21, 982
    addi     x5, x26, -1095       // ADDI x5, x26, -1095
    xori     x10, x18, -386       // XORI x10, x18, -386
    or       x22, x26, x13        // OR x22, x26, x13
    slti     x27, x19, -1357      // SLTI x27, x19, -1357
    and      x29, x21, x6         // AND x29, x21, x6
    add      x7, x24, x29         // ADD x7, x24, x29
    slli     x28, x21, 28         // SLLI x28, x21, 28
    srai     x13, x20, 12         // SRAI x13, x20, 12
    add      x18, x22, x7         // ADD x18, x22, x7
    subi     x14, x5, 1167        // SUBI x14, x5, 1167
    slti     x3, x20, 1909        // SLTI x3, x20, 1909
    xori     x19, x13, -1696      // XORI x19, x13, -1696
    sltiu    x1, x8, x14          // SLTIU x1, x8, x14
    addi     x11, x29, 256        // ADDI x11, x29, 256
    addi     x20, x27, 815        // ADDI x20, x27, 815
    srli     x8, x25, 10          // SRLI x8, x25, 10
    and      x11, x12, x20        // AND x11, x12, x20
    sll      x1, x23, x26         // SLL x1, x23, x26
    ori      x27, x31, 1281       // ORI x27, x31, 1281
    addi     x21, x21, 240        // ADDI x21, x21, 240
    srli     x25, x25, 16         // SRLI x25, x25, 16
    addi     x7, x20, -1165       // ADDI x7, x20, -1165
    addi     x24, x13, -1909      // ADDI x24, x13, -1909
    slti     x9, x26, -801        // SLTI x9, x26, -801
    slli     x6, x6, 22           // SLLI x6, x6, 22
    slti     x23, x14, -2048      // SLTI x23, x14, -2048
    xori     x5, x14, 1868        // XORI x5, x14, 1868
    add      x6, x14, x3          // ADD x6, x14, x3
    or       x2, x4, x12          // OR x2, x4, x12
    slt      x19, x8, x20         // SLT x19, x8, x20
    sub      x25, x17, x10        // SUB x25, x17, x10
    addi     x31, x13, 15         // ADDI x31, x13, 15
    andi     x30, x30, -963       // ANDI x30, x30, -963
    sll      x27, x15, x8         // SLL x27, x15, x8
    sub      x26, x26, x5         // SUB x26, x26, x5
    add      x1, x16, x30         // ADD x1, x16, x30
    srai     x20, x16, 21         // SRAI x20, x16, 21
    sub      x16, x22, x1         // SUB x16, x22, x1
    sll      x13, x2, x24         // SLL x13, x2, x24
    and      x31, x21, x9         // AND x31, x21, x9
    srai     x19, x3, 14          // SRAI x19, x3, 14
    srli     x5, x3, 14           // SRLI x5, x3, 14
    and      x26, x2, x31         // AND x26, x2, x31
    or       x7, x13, x8          // OR x7, x13, x8
    sltiu    x6, x14, x29         // SLTIU x6, x14, x29
    sltiu    x11, x24, x9         // SLTIU x11, x24, x9
    sub      x5, x9, x15          // SUB x5, x9, x15
    xori     x29, x2, 1           // XORI x29, x2, 1
    ori      x11, x12, -1460      // ORI x11, x12, -1460
    andi     x21, x6, 837         // ANDI x21, x6, 837
    and      x15, x28, x2         // AND x15, x28, x2
    sltiu    x31, x12, x15        // SLTIU x31, x12, x15
    or       x24, x10, x31        // OR x24, x10, x31
    ori      x5, x7, 2031         // ORI x5, x7, 2031
    sll      x19, x30, x29        // SLL x19, x30, x29
    andi     x18, x27, 256        // ANDI x18, x27, 256

    # Random Test Cases
    xor      x30, x7, x9          // XOR x30, x7, x9
    srl      x12, x4, x28         // SRL x12, x4, x28
    srl      x5, x7, x24          // SRL x5, x7, x24
    auipc    x1, 15               // AUIPC x1, 15
    auipc    x26, 1               // AUIPC x26, 1
    srl      x9, x19, x14         // SRL x9, x19, x14
    lui      x5, 733431           // LUI x5, 733431
    xor      x8, x7, x6           // XOR x8, x7, x6
    srl      x1, x22, x16         // SRL x1, x22, x16
    srl      x18, x17, x23        // SRL x18, x17, x23
    lui      x1, 16               // LUI x1, 16
    lui      x25, 682325          // LUI x25, 682325
    srl      x15, x14, x15        // SRL x15, x14, x15
    lui      x20, 0               // LUI x20, 0
    auipc    x30, 0               // AUIPC x30, 0
    xor      x8, x16, x12         // XOR x8, x16, x12
    srl      x21, x1, x17         // SRL x21, x1, x17
    sra      x1, x26, x31         // SRA x1, x26, x31
    xor      x23, x21, x7         // XOR x23, x21, x7
    sra      x1, x24, x13         // SRA x1, x24, x13
    srl      x11, x7, x5          // SRL x11, x7, x5
    sra      x17, x10, x18        // SRA x17, x10, x18
    lui      x25, 30036           // LUI x25, 30036
    srl      x16, x15, x23        // SRL x16, x15, x23
    sra      x16, x10, x27        // SRA x16, x10, x27
    lui      x29, 204439          // LUI x29, 204439
    srl      x28, x9, x30         // SRL x28, x9, x30
    srl      x1, x2, x5           // SRL x1, x2, x5
    sra      x6, x17, x7          // SRA x6, x17, x7
    lui      x29, 437576          // LUI x29, 437576
    xor      x23, x30, x8         // XOR x23, x30, x8
    auipc    x29, 771662          // AUIPC x29, 771662
    auipc    x18, 382243          // AUIPC x18, 382243
    xor      x14, x1, x5          // XOR x14, x1, x5
    xor      x19, x13, x14        // XOR x19, x13, x14
    xor      x14, x18, x18        // XOR x14, x18, x18
    xor      x26, x26, x16        // XOR x26, x26, x16
    sra      x3, x4, x15          // SRA x3, x4, x15
    srl      x27, x12, x15        // SRL x27, x12, x15
    xor      x20, x8, x11         // XOR x20, x8, x11
    sra      x25, x21, x17        // SRA x25, x21, x17
    auipc    x25, 1365            // AUIPC x25, 1365
    srl      x19, x14, x26        // SRL x19, x14, x26
    lui      x19, 16              // LUI x19, 16
    lui      x12, 937382          // LUI x12, 937382
    sra      x30, x8, x14         // SRA x30, x8, x14
    lui      x21, 281887          // LUI x21, 281887
    sra      x2, x7, x8           // SRA x2, x7, x8
    xor      x1, x7, x9           // XOR x1, x7, x9
    sra      x3, x2, x30          // SRA x3, x2, x30
    srl      x21, x6, x25         // SRL x21, x6, x25
    xor      x3, x8, x1           // XOR x3, x8, x1
    sra      x30, x3, x15         // SRA x30, x3, x15
    xor      x26, x17, x9         // XOR x26, x17, x9
    lui      x30, 44570           // LUI x30, 44570
    xor      x16, x6, x5          // XOR x16, x6, x5
    xor      x13, x23, x13        // XOR x13, x23, x13
    xor      x1, x6, x14          // XOR x1, x6, x14
    sra      x18, x14, x16        // SRA x18, x14, x16
    srl      x8, x17, x26         // SRL x8, x17, x26
    sra      x9, x31, x7          // SRA x9, x31, x7
    auipc    x5, 782765           // AUIPC x5, 782765
    lui      x6, 843569           // LUI x6, 843569
    sra      x29, x10, x3         // SRA x29, x10, x3
    sra      x4, x11, x22         // SRA x4, x11, x22
    srl      x3, x21, x31         // SRL x3, x21, x31
    xor      x27, x12, x15        // XOR x27, x12, x15
    auipc    x10, 171975          // AUIPC x10, 171975
    lui      x24, 806229          // LUI x24, 806229
    xor      x30, x3, x31         // XOR x30, x3, x31
    sra      x31, x22, x8         // SRA x31, x22, x8
    xor      x16, x12, x16        // XOR x16, x12, x16
    srl      x14, x2, x10         // SRL x14, x2, x10
    lui      x26, 374317          // LUI x26, 374317
    xor      x3, x9, x17          // XOR x3, x9, x17
    auipc    x7, 651494           // AUIPC x7, 651494
    lui      x4, 699079           // LUI x4, 699079
    lui      x13, 1               // LUI x13, 1
    sra      x7, x17, x4          // SRA x7, x17, x4
    auipc    x20, 317260          // AUIPC x20, 317260
    auipc    x25, 240             // AUIPC x25, 240
    xor      x29, x12, x30        // XOR x29, x12, x30
    xor      x28, x26, x26        // XOR x28, x26, x26
    xor      x30, x29, x24        // XOR x30, x29, x24
    sra      x23, x22, x27        // SRA x23, x22, x27
    sra      x19, x13, x15        // SRA x19, x13, x15
    srl      x19, x5, x22         // SRL x19, x5, x22
    srl      x26, x12, x20        // SRL x26, x12, x20
    sra      x10, x9, x22         // SRA x10, x9, x22
    auipc    x11, 16              // AUIPC x11, 16
    xor      x11, x23, x26        // XOR x11, x23, x26
    xor      x16, x4, x6          // XOR x16, x4, x6
    sra      x8, x1, x7           // SRA x8, x1, x7
    auipc    x6, 0                // AUIPC x6, 0
    auipc    x30, 719640          // AUIPC x30, 719640
    lui      x6, 1                // LUI x6, 1
    xor      x21, x11, x26        // XOR x21, x11, x26
    auipc    x17, 680215          // AUIPC x17, 680215
    auipc    x28, 85857           // AUIPC x28, 85857
    lui      x18, 454402          // LUI x18, 454402
    srl      x28, x2, x17         // SRL x28, x2, x17
    lui      x18, 447013          // LUI x18, 447013
    sra      x21, x28, x20        // SRA x21, x28, x20
    sra      x21, x23, x24        // SRA x21, x23, x24
    xor      x19, x19, x29        // XOR x19, x19, x29
    lui      x6, 16               // LUI x6, 16
    auipc    x6, 762653           // AUIPC x6, 762653
    auipc    x30, 935163          // AUIPC x30, 935163
    lui      x10, 777160          // LUI x10, 777160
    xor      x22, x14, x14        // XOR x22, x14, x14
    sra      x11, x29, x29        // SRA x11, x29, x29
    lui      x12, 256             // LUI x12, 256
    xor      x6, x27, x11         // XOR x6, x27, x11
    sra      x22, x19, x27        // SRA x22, x19, x27
    auipc    x24, 19613           // AUIPC x24, 19613
    xor      x17, x29, x10        // XOR x17, x29, x10
    lui      x11, 0               // LUI x11, 0
    sra      x15, x11, x23        // SRA x15, x11, x23
    xor      x27, x25, x23        // XOR x27, x25, x23
    auipc    x13, 342836          // AUIPC x13, 342836
    srl      x28, x29, x6         // SRL x28, x29, x6
    srl      x27, x26, x31        // SRL x27, x26, x31
    srl      x17, x7, x12         // SRL x17, x7, x12
    xor      x18, x25, x23        // XOR x18, x25, x23
    lui      x7, 105865           // LUI x7, 105865
    srl      x22, x13, x27        // SRL x22, x13, x27
    sra      x30, x19, x26        // SRA x30, x19, x26
    srl      x22, x1, x27         // SRL x22, x1, x27
    srl      x20, x21, x28        // SRL x20, x21, x28

    # Program termination
    addi    x1, x0, 93      // sys_exit
    addi    x10, x0, 0      // exit status
    ecall                   // system call
